### ISSUE TITLE
Bug found (Megastructure Error)

### ISSUE THREAD

**Issue by CaptainX3** [CaptainX3/NSC2-Issues-Board#27]
Submitter: Lord Trayus
Email: jesse.john.orellana@gmail.com
I was looking at superstructures and found a couple of blank structures that were traced back to this mod.  It's probably just an issue with the menu, but the blank structures show up as {ai-setup] or something similar.  I hope this was helpful.

**Comment by CaptainX3** [comment]
We just pushed an update to fix this error. Please read the info on the Steam page regarding the update, as the error was game-breaking.

**Comment by sandman077** [comment]
[https://drive.google.com/open?id=190Ml4lB5lIPZVTJorPfjHb3rLlwcvn9_](url)
