### ISSUE TITLE
Battlecruiser Section L2M1 Bug

### ISSUE THREAD

**Issue by NightskyPirate** [CaptainX3/NSC2-Issues-Board#32]
For the MID2 section.

ship_section_template = {
	key = "BATTLECRUISER_MID2_L2M1"
	ship_size = Battlecruiser
	fits_on_slot = mid2
	**entity = "Battlecruiser_mid1_L1M1_entity"**
	icon = "GFX_ship_part_core_mid"

Bolded line- should be 
entity = "Battlecruiser_**mid2**_L1M1_entity

Causes graphical issues with mods with custom ships using compatibility with NSC.

**Comment by CaptainX3** [comment]
Thanks for the report, added to the fix list!
