### ISSUE TITLE
A series of conflicting files

### ISSUE THREAD

**Issue by Sunconure11** [CaptainX3/NSC2-Issues-Board#33]
I'm trying to investigate what could be causing the starbase ship menu to be a bit too big for my screen, and I found these files from various mods conflict with your mod. If you have any patches, or aware of any, for these mods, please post them as a response.

```
~Glavius's Ultimate AI for 2.2.7 :
	common\section_templates\battleship.txt
	common\section_templates\corvette.txt
	common\section_templates\cruiser.txt
	common\section_templates\destroyer.txt
	common\section_templates\other.txt
	common\ship_sizes\00_ship_sizes.txt
	common\ship_sizes\00_starbases.txt

!!AlphaMod/GAI CP (2.2.7) :
	common\ship_sizes\00_starbases.txt

Guilli's Ship Components 2.2 :
	common\section_templates\battleship.txt
	common\section_templates\corvette.txt
	common\section_templates\cruiser.txt
	common\section_templates\destroyer.txt
	common\section_templates\titan.txt
	common\ship_sizes\00_ship_sizes.txt

Backgrounds+ Collection: 2.1+ :
	gfx\loadingscreens\load_10.dds
	gfx\loadingscreens\load_11.dds
	gfx\loadingscreens\load_2.dds
	gfx\loadingscreens\load_5.dds
	gfx\loadingscreens\load_6.dds
	gfx\loadingscreens\load_8.dds

AlphaMod 2.2.7 (Beta) :
	common\ship_sizes\00_starbases.txt
	gfx\interface\main\game_logo.dds

Psionic Re-Expanded :
	common\ship_sizes\00_ship_sizes.txt
```

**Comment by Sunconure11** [comment]
![Screenshot 2019-04-11 17 23 35](https://user-images.githubusercontent.com/5614902/55994011-9790e180-5c7e-11e9-924d-72c17522dc8f.png)

This is an example of the bug I'm trying to deal with, BTW.

**Comment by CaptainX3** [comment]
~Glavius's Ultimate AI for 2.2.7 - No patch needed, the two mods will work together without issue.

!!AlphaMod/GAI CP (2.2.7) - No known patch at this time.

Guilli's Ship Components 2.2 - https://steamcommunity.com/sharedfiles/filedetails/?id=1706486754

Backgrounds+ Collection: 2.1+ - No known patch, but these files are just the NSC2 loading screens, they won't affect the functionality of either mod at all.

AlphaMod 2.2.7 (Beta) - No known patch at this time.

Psionic Re-Expanded - There is a patch someone made that will work for this mod, but it also includes files for Guilli's Ship Components and ISB Balance. I don't know how it'll work if you don't have all 3 mods (NSC2, GSC, and ISB). Here's the patch: https://steamcommunity.com/sharedfiles/filedetails/?id=1706232148

As for the bug with your screen, NSC2 requires use of a 1080p UI mod to make the starbase screens work properly. There are several available on the workshop, such as 1080p UI Plus and 1080p/1440p UI. If you run at a resolution less than 1920x1080, then you can still use a 1080p mod and change the UI Scaling option in the game settings to around 0.7. That's the only known fix for lower resolutions, as our changes to starbases and ship classes cannot fit on anything smaller.

**Comment by Sunconure11** [comment]
Yeah, my resolution is lower than that. Though I do have another monitor I'm willing to give a try.
