### ISSUE TITLE
Drydock issue.

### ISSUE THREAD

**Issue by Inei** [CaptainX3/NSC2-Issues-Board#34]
I think there is a bug with requirements for drydock starbase building, as in latest version I previously played (it was 2.1 game version) it was unique empire building and required shipyard to be constructed first. But now it is not only unique, it is actually not even requires shipyard and you can actually build it even on outpost without any limitations, which makes it quite OP.

**Comment by CaptainX3** [comment]
Outposts have no slots in NSC2, so you should be able to build anything on them, including Drydocks. If you have another mod that adds slots to Outposts, we have no control over that and we don't balance around other mods. The building is actually working as intended.
