### ISSUE TITLE
Game crashes at random times

### ISSUE THREAD

**Issue by RealXathras** [CaptainX3/NSC2-Issues-Board#36]
Hello,

i got the following problem:
I can start a new game, everything works fine. When i  progress further into it, at a seemingly random time the game freezes for 3 seconds and then exits to the desktop. When i reload the game, it will crash at exactly the same time. 
When i deactivate the NSC2 - Season 3 - Episode 3 Version 3.3.* mod and start a new game, everything is fine and i can play far beyond the late game.

game-log file comes with this:

> [19:14:10][effect_impl.cpp:18124]: [2210.4.1] Log command triggered from effect in file: common/mandates/00_mandates.txt line: 271. mandate_monthly_consumer_goods end_of_term fired for AI

> [19:14:10][effect_impl.cpp:18124]: [2210.4.1] Log command triggered from effect in file: events/mandate_events.txt line: 642. .170 active

> [19:14:10][effect_impl.cpp:18124]: [2210.4.1] Log command triggered from effect in file: common/mandates/00_mandates.txt line: 190. mandate_monthly_minerals end_of_term fired for AI

> [19:14:10][effect_impl.cpp:18124]: [2210.4.1] Log command triggered from effect in file: common/mandates/00_mandates.txt line: 27. mandate_orbital_researcher end_of_term fired for AI

> [19:14:10][effect_impl.cpp:18124]: [2210.4.1] Log command triggered from effect in file: common/mandates/00_mandates.txt line: 163. mandate_monthly_energy end_of_term fired for AI

and three seconds later, error-log file tells me this:

> [19:17:01][bitmapfont.cpp:2827]: Could not find coloring for character 'Z'

> [19:17:11][trigger.cpp:391]: invalid scope for trigger. got [fleet], expected {archaeological_site}.  file:  file: common/archaeological_site_types/01_site_types_dee.txt line: 216 line: 1

> [19:17:27][trigger.cpp:391]: invalid scope for trigger. got [fleet], expected {archaeological_site}.  file:  file: common/archaeological_site_types/arc_sites_henrik.txt line: 367 line: 1

these are the last errors in my logs.

Apart from this, i get a hell of "missing localization keys", "invalid component slots" and "object with key" - errors. Would be too long to post this but if it is necessary then i will.

Other two mods i have installed are: 
UI Overhaul 1080plus
Glavius Ultimate AI 2.3

already tried to deactivate them and only let the NSC mod active. Cheated resources so i could progress faster and maybe get to a crashing point faster.

My specifications if they are needed:

Win7
AMD FX 8350
Gainward GTX 960
16GB RAM
2 x 1TB HDD

Hope i got everything right and more importantly this is the right place for this.

Greetings

**Comment by CaptainX3** [comment]
common/mandates/00_mandates.txt
common/archaeological_site_types/01_site_types_dee.txt
common/archaeological_site_types/arc_sites_henrik.txt

Those are the files in your error log, but NSC2 doesn't have any of those files. If you're missing a lot of localisation and having component slot problems and you're not running any mods other than the two you posted above, it sounds like Steam botched the download of your copy of the mod. Try the steps below:

**HOW TO RESET NSC2:** If your copy of the mod is not working properly, delete this entire folder from your PC: Steam\SteamApps\workshop\content\281990\683230077 and then unsubscribe and resubscribe to the mod. Verify that Steam is downloading the mod, and then try to run again. **You may have to repeat this step a few times to get it working.** This is a common problem with Steam and we cannot fix it from our end.

**Comment by RealXathras** [comment]
Hello,

i did all this and now it wont crash anymore. Thank you very much!

Greetings
