### ISSUE TITLE
Staircase Menu/view

### ISSUE THREAD

**Issue by CaptainX3** [CaptainX3/NSC2-Issues-Board#38]
Submitter: Boyd Horton
I am running 2.3 with all DLC's and only your mod loaded. My screen resolution is 1920x1080. When I click on a starbase and the main view opens, it is too big to fit on the screen and the top part is cut off from view.

**Comment by bhorton22** [comment]
![image](https://user-images.githubusercontent.com/20910591/59155530-7b7ca700-8a59-11e9-83d8-7176373d714d.png)

**Comment by bhorton22** [comment]
After some more testing this only happens when you run the game in windowed mode (which the game does default to)

**Comment by CaptainX3** [comment]
You also need the 1080p UI mod linked under "Required Items" on the Steam page.
