### ISSUE TITLE
Light Carrier Piracy Suppression

### ISSUE THREAD

**Issue by CaptainX3** [CaptainX3/NSC2-Issues-Board#5]
_Submitted by Creature_

Can we have light carriers be extremely good at piracy suppression?

**_Developer Comment: We could possibly implement this by adding a piracy suppression modifier to the Light Carrier tech. It would apply to all BCs afterwards, but I don't see that as an issue._**

**Comment by CaptainX3** [comment]
We have verified that it is not possible to add extra piracy suppression via tech. We may look at this in the future to see if it can be done via a component, but not for the first Season 3 release.

**Comment by ImperialHouse200** [comment]
booo
